### ISSUE TITLE
Configure GitHub Actions

### ISSUE THREAD

**Issue by su8ru** [su8ru/kostl#1]
この辺参考に
cacheは抜いてyarnに置き換えればいいのかな
`publish_dir: ./public` でいいの…？

https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d#nodejs-javascript-%E7%B3%BB

```yaml
name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: build
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
```
